untitled/6.0-全栈开发阶段/Django框架/dailyfresh/apps/cart/urls.py
from django.conf.urls import url
from cart.views import CartAddViews,CartInfoViews,CartUpdateViews,CartDeleteViews
urlpatterns = [
    url(r'^add$',CartAddViews.as_view(), name='add'),   # 购物车添加商品
    url(r'^$',CartInfoViews.as_view(), name='show'),    # 购物车页面显示
    url(r'^update$',CartUpdateViews.as_view(), name='update'),  # 购物车记录更新
    url(r'^delete$',CartDeleteViews.as_view(), name='delete'),  # 购物车记录删除

]

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexViews, DetailViews, ListViews

urlpatterns = [
    url(r'^index$',IndexViews.as_view(),name='index'),     # 显示首页
    url(r'^goods/(?P<goods_id>\d+)$',DetailViews.as_view(),name='detail'),    # 显示详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListViews.as_view(),name='list'),  # 显示列表页
]

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/apps/user/urls.py
from django.conf.urls import url
from user.views import RegisterViews,ActiveViews,LoginViews,UserInfoViews,UserOrderViews,AddressViews,LogoutViews,DeleteViews,AddressDeleteViews,UpdateDefaultViews
from django.contrib.auth.decorators import login_required
from user import views
urlpatterns = [
    #url(r'^register$',views.register,name='register'),  # 用户注册页面
    #url(r'^register_handle$',views.register_handle,name='register_handle'),    # 用户注册处理

    url(r'^register$',RegisterViews.as_view(),name='register'),  # 用户注册以及处理
    url(r'^active/(?P<token>.*)$',ActiveViews.as_view(),name='active'),    # 用户激活

    url(r'^login$', LoginViews.as_view(), name='login'),  # 用户登入
    url(r'^logout$', LogoutViews.as_view(), name='logout'),   # 用户注销

    # url(r'^$',login_required(UserInfoViews.as_view()),name='user'),  # 用户中心-信息页
    # url(r'^order$',login_required(UserOrderViews.as_view()),name='order'),  # 用户中心-订单页
    # url(r'^address$',login_required(AddressViews.as_view()),name='address'),     # 用户中心-地址页

    url(r'^$', UserInfoViews.as_view(), name='user'),  # 用户中心-信息页
    url(r'^order/(?P<page>\d+)$', UserOrderViews.as_view(), name='order'),  # 用户中心-订单页
    url(r'^address$', AddressViews.as_view(), name='address'),  # 用户中心-地址页

    # url(r'^delete(?P<pid>\d+)$', DeleteViews.as_view(), name='delete'),  # 删除地址
url(r'^delete$', AddressDeleteViews.as_view(), name='delete'),  # 删除地址
    url(r'^update$', UpdateDefaultViews.as_view(), name='update'),    # 更新默认地址
]

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')), # 富文本编辑器
    url(r'^search$', include('haystack.urls')), # 全文检索框架
    url(r'^user/', include('user.urls', namespace='user')), # 用户模块
    url(r'^cart/', include('cart.urls', namespace='cart')), # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')), # 订单模块
    url(r'^', include('goods.urls', namespace='goods')), # 商品模块
]

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from utils.mixin import LoginRequiredMixin
from django_redis import get_redis_connection
# Create your views here.
# 添加商品到购物车：
# 1)请求方式，采用ajax：post
# 如果涉及到数据的修改(增删改)，则采用post
# 只涉及到数据的传递，则采用get
# 2)传递参数：商品id(sku_id), 商品数量(count)

# ajax请求都在后台，所以不能继承utils中的LoginRequiredMixin()，页面不会跳转，
# ajax中post请求也需要csrf_token;将csrf_token放在某个input提交中提交过来
# /cart/add
class CartAddViews(View):
    '''购物车记录添加商品'''
    def post(self,request):
        '''购物车添加记录'''
        # 先判断用户是否登录
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res':0,'errmsg':'请先登入'})
        # 1.接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 2.进行数据校验
        # 2.1第一步校验：数据完整性
        if not all([sku_id,count]):
            # 数据不完整
            return JsonResponse({'res':1, 'errmsg':'数据不完整'})
        # 2.2第二步校验：用户添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数据不合法
            return JsonResponse({'res':2,'errmsg':'商品数目出错'})
        # 2.3第三步校验：商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res':3, 'errmsg': '商品不存在'})
        # 3.业务处理：进行购物车数据添加
        # 获取redis中的数据
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # 先尝试获取数据库中的sku_id的数量-->hget(cart_key,属性)
        # 如果sku_id在hash中不存在值，hget返回None
        cart_count = conn.hget(cart_key,sku_id)
        if cart_count:
            # 如果有值,累加购物车中的数量
            count += int(cart_count)
        # 判断加入购物车中的数量是否大于库存
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品的库存不足'})

        # 设置hash中的sku_id对应的值，hash中不存在的值，hset相当于新增
        conn.hset(cart_key,sku_id,count)

        # 计算用户购物车中的条目数
        total_count = conn.hlen(cart_key)
        # 4.返回应答
        return JsonResponse({'res':5,'total_count':total_count,'errmsg':'加入购物车成功'})

# /cart
class CartInfoViews(LoginRequiredMixin,View):
    '''购物车页面'''
    def get(self,request):
        '''显示购物车页面'''
        # 获取登入的用户
        user = request.user
        # 获取用户购物车中的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # {'商品id':商品数量}
        cart_dict = conn.hgetall(cart_key)

        # 定义一个空列表存放增加属性了的商品sku对象
        skus=[]
        # 保存用户购物车中的商品总件数和商品总价数
        total_count = 0
        total_price = 0
        # 遍历字典中的键和值
        for sku_id, count in cart_dict.items():
            # print(sku_id,count)
            # 根据商品id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 获取商品单价
            price = sku.price
            # 单个商品小计
            amount = price*int(count)
            # 动态的给对象增加属性
            sku.count = count
            sku.amount = amount
            # 将对象加入列表中
            skus.append(sku)
            # 商品总件数和总价
            total_count +=int(count)
            total_price +=amount
        # 组织上下文
        context = {'total_count':total_count,
                   'total_price':total_price,
                   'skus':skus}
        return render(request,'cart.html',context)

# 更新购物车记录
# 采用ajax  post请求
# 前端需要传过来的参数：商品id(sku_id), 更新商品数量(count)
# /cart/update
class CartUpdateViews(View):
    '''购物车记录更新'''
    def post(self,request):
        '''购物车记录更新'''
        # 获取用户
        user = request.user
        if not user.is_authenticated():
            # 用户未登入
            return JsonResponse({'res': 0, 'errmsg':'用户未登入'})
        # 1.接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 2.进行数据校验
        # 2.1第一步校验：数据完整性
        if not all([sku_id, count]):
            # 数据不完整
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 2.2第二步校验：用户添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数据不合法
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        # 2.3第三步校验：商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})
        # 3.业务处理：进行购物车数据添加
        # 获取redis中的数据
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # 判断加入购物车中的数量是否大于库存
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品的库存不足'})
        # 更新数据库中的数量
        conn.hset(cart_key, sku_id, count)
         # {'商品id':商品数量}
        total_count = 0
        # 求购物车商品总数量 方法一
        cart_dict = conn.hgetall(cart_key)
        for count in cart_dict.values():
            total_count +=int(count)
        # 求购物车商品总数量 方法二
        # vals = conn.hvals(cart_key)
        # for count in vals:
        #     total_count +=int(count)
        # 返回应答
        return JsonResponse({'res':5, 'total_count':total_count, 'message': '更新成功'})

# 删除购物车数据
# 采用ajax  post请求
# 前端需要传过来的参数：商品id(sku_id),
# /cart/delete
class CartDeleteViews(View):
    '''删除购物车数据'''
    def post(self,request):
        '''购物车记录数据'''
        user = request.user
        if not user.is_authenticated():
            # 用户未登入
            return JsonResponse({'res':1, 'errmsg':'用户未登入'})

        # 获取数据
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 2, 'errmsg': '无效商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：购物车记录删除
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 删除数据
        conn.hdel(cart_key, sku_id)
        # 求购物车商品总数量
        total_count = 0
        vals = conn.hvals(cart_key)
        for count in vals:
            total_count +=int(count)
        # 返回应答
        return JsonResponse({'res': 4,'total_count':total_count, 'message': '删除成功'})

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/templates/base.html
{# 首页 注册 登入 详情页 列表页 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title%}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部文件引入块 #}
    {% block topfiles %}{% endblock topfiles%}
</head>
<body>
{# 网页顶部欢迎页 #}
{% block header_con %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {# 设置欢迎信息，判断登入状态， #}
                {% if  user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
                </div>
                {% else  %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con%}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{# 网页底部html元素块 #}
{% block buttom %}{% endblock buttom%}

{# 网页底部文件引入块 #}
{% block buttomfiles %}{% endblock buttomfiles %}
</body>
</html>

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/templates/base_detail_list.html
{# 详情页 主体页 #}

{% extends 'base.html' %}

{# 网页主体内容 #}
{% block body %}
    	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页、列表页主体内容 #}
    {% block main_center%} {% endblock main_center%}


{% endblock body %}




untitled/6.0-全栈开发阶段/Django框架/dailyfresh/templates/base_no_cart.html
{# 购物车  提交订单  用户中心3个页面#}

{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title%}{% endblock page_title%}</div>
		<div class="search_con fr">
			<form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/templates/base_user_center.html
{# 用户中心3个页面 #}
{% extends 'base_no_cart.html' %}
{% block title %} 天天生鲜-用户中心{% endblock title%}
{% block page_title %} 用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容 #}
        {% block right_content %}{% endblock right_content %}
    </div>

{% endblock body %}

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页 {% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
{#                #model0{{ forloop.counter }}#}
			<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for  banner in goods_banners %}
				<li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
			{% endfor %}
		</div>
	</div>
    
    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}


untitled/6.0-全栈开发阶段/Django框架/dailyfresh/templates/list.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_center %}
	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type.id 1 %}">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %} class="active" {% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %} class="active" {% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %} class="active" {% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page.object_list %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="javascript:;" class="add_goods" sku_id="{{ sku.id }}" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
                <a href="{% url 'goods:list' type.id skus_page.previous_page_number%}?sort={{ sort }}">&lt上一页</a>
                {% endif %}

                {% for pindex in pages%}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' type.id pindex%}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex%}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% endif %}
                 {% endfor %}

                {% if skus_page.has_next %}
                <a href="{% url 'goods:list' type.id skus_page.next_page_number%}?sort={{ sort }}">下一页&gt</a>
                {% endif %}
			</div>
		</div>

        {% csrf_token %}
	</div>

{% endblock main_center %}
{% block buttom %}
	<div class="add_jump"></div>
{% endblock buttom %}
{% block buttomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>


        var $add_x = $('.add_goods').offset().top;
        var $add_y = $('.add_goods').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $('.add_goods').click(function () {
            // 获取商品id和商品数量
            sku_id = $(this).attr('sku_id');    // 获取自定义属性
            //count = $('#show_count').text();
            count = 1
            //alert(sku_id+':'+count)
            csrf =$('input[name="csrfmiddlewaretoken"]').val();
            params = {'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf};
           $.post('/cart/add',params,function (data) {
                if (data.res == 5) {
                    //添加成功
                    // alert(data.errmsg)
                     $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast', function () {
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
                    });
                }
                else{
                    // 添加失败
                    alert(data.errmsg)
                }

            });
        });

    </script>
{% endblock buttomfiles %}

untitled/6.0-全栈开发阶段/Django框架/dailyfresh/templates/static_base.html
{# 首页 注册 登入 详情页 列表页 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title%}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部文件引入块 #}
    {% block topfiles %}{% endblock topfiles%}
</head>
<body>
{# 网页顶部欢迎页 #}
{% block header_con %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con%}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{# 网页底部html元素块 #}
{% block buttom %}{% endblock buttom%}

{# 网页底部文件引入块 #}
{% block buttomfiles %}{% endblock buttomfiles %}
</body>
</html>